common: Kconfig: Fix CMD_BMP/BMP dependency
Using `default y` will not select BMP when CMD_BMP has been enabled, if
it was already configured.

By using `depends on`, if `CMD_BMP` is turned on, it will force the presence
of `BMP`.

Reproduced by:

```
make pinebook_defconfig
make menuconfig
(enabling CMD_BMP)
make
```

Ends-up with:

```
aarch64-unknown-linux-gnu-ld.bfd: boot/pxe_utils.o: in function `handle_pxe_menu':
.../u-boot/2023.07-rc6/boot/pxe_utils.c:1541: undefined reference to `bmp_display'
aarch64-unknown-linux-gnu-ld.bfd: cmd/bmp.o: in function `do_bmp_display':
.../u-boot/2023.07-rc6/cmd/bmp.c:68: undefined reference to `bmp_display'
aarch64-unknown-linux-gnu-ld.bfd: cmd/bmp.o: in function `do_bmp_info':
.../u-boot/2023.07-rc6/cmd/bmp.c:35: undefined reference to `bmp_info'
```

Fixes: 072b0e16c4 ("common: Kconfig: Add BMP configs")
Signed-off-by: Samuel Dionne-Riel <samuel@dionne-riel.com>